<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="xSoftware" nsURI="http://www.uniandes.edu.co/xsoftware" nsPrefix="xSoftware">
  <eClassifiers xsi:type="ecore:EClass" name="Api">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entidades" upperBound="-1"
        eType="#//Entidad" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primitivetypes" upperBound="-1"
        eType="#//PrimitiveType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviciosRest" upperBound="-1"
        eType="#//ServicioRest" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tests" upperBound="-1"
        eType="#//Test" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServicioRest">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entidades" lowerBound="1"
        upperBound="-1" eType="#//Entidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metodo" eType="#//TipoMetodoRest"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="response" lowerBound="1"
        eType="#//Response" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entidad">
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributos" lowerBound="1"
        upperBound="-1" eType="#//Atributo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atributo" eSuperTypes="#//Elemento">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mockType" eType="#//Mockaroo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="#//TipoAtributo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Response">
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributos" lowerBound="1"
        upperBound="-1" eType="#//Atributo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parametro">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="#//TipoParametro"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descripcion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//Mapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" lowerBound="1"
        eType="#//ServicioRest"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asertions" upperBound="-1"
        eType="#//Asercion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asercion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elemento1" lowerBound="1"
        eType="#//Elemento"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elemento2" lowerBound="1"
        eType="#//Elemento"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoMetodoRest">
    <eLiterals name="GET"/>
    <eLiterals name="POST" value="1"/>
    <eLiterals name="PUT" value="2"/>
    <eLiterals name="DELETE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoParametro">
    <eLiterals name="Path"/>
    <eLiterals name="Query" value="1"/>
    <eLiterals name="Body" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" abstract="true" eSuperTypes="#//Elemento"/>
  <eClassifiers xsi:type="ecore:EClass" name="Elemento" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MyNumeric" eSuperTypes="#//PrimitiveType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MyString" eSuperTypes="#//PrimitiveType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MyBoolean" eSuperTypes="#//PrimitiveType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Mockaroo">
    <eLiterals name="FirstNameType"/>
    <eLiterals name="LastNameType" value="1"/>
    <eLiterals name="FamilyNameType" value="2"/>
    <eLiterals name="FullNameType" value="3"/>
    <eLiterals name="GenderType" value="4"/>
    <eLiterals name="EmailAddressType" value="5"/>
    <eLiterals name="PhoneType" value="6"/>
    <eLiterals name="CountryType" value="7"/>
    <eLiterals name="CityType" value="8"/>
    <eLiterals name="CountryCodeType" value="9"/>
    <eLiterals name="LatitudeType" value="10"/>
    <eLiterals name="LongitudType" value="11"/>
    <eLiterals name="RowNumberType" value="12"/>
    <eLiterals name="BooleanType" value="13"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtributoArreglo" eSuperTypes="#//Atributo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementos" upperBound="-1"
        eType="#//Elemento"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Elemento"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametro" lowerBound="1"
        eType="#//Parametro" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoAtributo">
    <eLiterals name="string"/>
    <eLiterals name="int" value="1"/>
    <eLiterals name="boolean" value="2"/>
  </eClassifiers>
</ecore:EPackage>
