/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ApiElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Api");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cApiAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cApiURLKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cEQUALTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cUrlAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cUrlEStringParserRuleCall_3_0 = (RuleCall)cUrlAssignment_3.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Assignment cEntidadesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cEntidadesEntidadParserRuleCall_5_0 = (RuleCall)cEntidadesAssignment_5.eContents().get(0);
		
		//Api:
		//	{Api}
		//	'apiURL' EQUAL url=EString SEMICOLON
		//	entidades+=Entidad*
		//	/**primitivetypes+=PrimitiveType
		//		serviciosRest+=ServicioRest
		//		tests+=Test**/;
		@Override public ParserRule getRule() { return rule; }
		
		//{Api} 'apiURL' EQUAL url=EString SEMICOLON entidades+=Entidad*
		public Group getGroup() { return cGroup; }
		
		//{Api}
		public Action getApiAction_0() { return cApiAction_0; }
		
		//'apiURL'
		public Keyword getApiURLKeyword_1() { return cApiURLKeyword_1; }
		
		//EQUAL
		public RuleCall getEQUALTerminalRuleCall_2() { return cEQUALTerminalRuleCall_2; }
		
		//url=EString
		public Assignment getUrlAssignment_3() { return cUrlAssignment_3; }
		
		//EString
		public RuleCall getUrlEStringParserRuleCall_3_0() { return cUrlEStringParserRuleCall_3_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_4() { return cSEMICOLONTerminalRuleCall_4; }
		
		//entidades+=Entidad*
		public Assignment getEntidadesAssignment_5() { return cEntidadesAssignment_5; }
		
		//Entidad
		public RuleCall getEntidadesEntidadParserRuleCall_5_0() { return cEntidadesEntidadParserRuleCall_5_0; }
	}
	public class EntidadElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Entidad");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSimpleEntityParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cMockarooEntityParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Entidad:
		//	SimpleEntity | MockarooEntity;
		@Override public ParserRule getRule() { return rule; }
		
		//SimpleEntity | MockarooEntity
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SimpleEntity
		public RuleCall getSimpleEntityParserRuleCall_0() { return cSimpleEntityParserRuleCall_0; }
		
		//MockarooEntity
		public RuleCall getMockarooEntityParserRuleCall_1() { return cMockarooEntityParserRuleCall_1; }
	}
	public class PrimitiveTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.PrimitiveType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMyNumericParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cMyStringParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cMyBooleanParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//PrimitiveType:
		//	MyNumeric | MyString | MyBoolean;
		@Override public ParserRule getRule() { return rule; }
		
		//MyNumeric | MyString | MyBoolean
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//MyNumeric
		public RuleCall getMyNumericParserRuleCall_0() { return cMyNumericParserRuleCall_0; }
		
		//MyString
		public RuleCall getMyStringParserRuleCall_1() { return cMyStringParserRuleCall_1; }
		
		//MyBoolean
		public RuleCall getMyBooleanParserRuleCall_2() { return cMyBooleanParserRuleCall_2; }
	}
	public class AtributoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Atributo");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAtributoMockaParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAtributoArregloParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cAtributoSimpleParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Atributo:
		//	AtributoMocka | AtributoArreglo | AtributoSimple;
		@Override public ParserRule getRule() { return rule; }
		
		//AtributoMocka | AtributoArreglo | AtributoSimple
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//AtributoMocka
		public RuleCall getAtributoMockaParserRuleCall_0() { return cAtributoMockaParserRuleCall_0; }
		
		//AtributoArreglo
		public RuleCall getAtributoArregloParserRuleCall_1() { return cAtributoArregloParserRuleCall_1; }
		
		//AtributoSimple
		public RuleCall getAtributoSimpleParserRuleCall_2() { return cAtributoSimpleParserRuleCall_2; }
	}
	public class AtributoMockaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.AtributoMocka");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTipoAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTipoTipoAtributoEnumRuleCall_0_0 = (RuleCall)cTipoAssignment_0.eContents().get(0);
		private final Assignment cNombreAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNombreEStringParserRuleCall_1_0 = (RuleCall)cNombreAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftParenthesisKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Alternatives cAlternatives_2_1 = (Alternatives)cGroup_2.eContents().get(1);
		private final Group cGroup_2_1_0 = (Group)cAlternatives_2_1.eContents().get(0);
		private final Assignment cPrimaryKeyAssignment_2_1_0_0 = (Assignment)cGroup_2_1_0.eContents().get(0);
		private final Keyword cPrimaryKeyPKMockTypeKeyword_2_1_0_0_0 = (Keyword)cPrimaryKeyAssignment_2_1_0_0.eContents().get(0);
		private final RuleCall cEQUALTerminalRuleCall_2_1_0_1 = (RuleCall)cGroup_2_1_0.eContents().get(1);
		private final Assignment cMockTypeAssignment_2_1_0_2 = (Assignment)cGroup_2_1_0.eContents().get(2);
		private final RuleCall cMockTypeMockarooEnumRuleCall_2_1_0_2_0 = (RuleCall)cMockTypeAssignment_2_1_0_2.eContents().get(0);
		private final Group cGroup_2_1_1 = (Group)cAlternatives_2_1.eContents().get(1);
		private final Keyword cMockTypeKeyword_2_1_1_0 = (Keyword)cGroup_2_1_1.eContents().get(0);
		private final RuleCall cEQUALTerminalRuleCall_2_1_1_1 = (RuleCall)cGroup_2_1_1.eContents().get(1);
		private final Assignment cMockTypeAssignment_2_1_1_2 = (Assignment)cGroup_2_1_1.eContents().get(2);
		private final RuleCall cMockTypeMockarooEnumRuleCall_2_1_1_2_0 = (RuleCall)cMockTypeAssignment_2_1_1_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final RuleCall cSEMICOLONTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		
		//AtributoMocka:
		//	tipo=TipoAtributo nombre=EString ('(' (primaryKey?='PK,mockType' EQUAL mockType=Mockaroo | 'mockType' EQUAL
		//	mockType=Mockaroo) ')') SEMICOLON;
		@Override public ParserRule getRule() { return rule; }
		
		//tipo=TipoAtributo nombre=EString ('(' (primaryKey?='PK,mockType' EQUAL mockType=Mockaroo | 'mockType' EQUAL
		//mockType=Mockaroo) ')') SEMICOLON
		public Group getGroup() { return cGroup; }
		
		//tipo=TipoAtributo
		public Assignment getTipoAssignment_0() { return cTipoAssignment_0; }
		
		//TipoAtributo
		public RuleCall getTipoTipoAtributoEnumRuleCall_0_0() { return cTipoTipoAtributoEnumRuleCall_0_0; }
		
		//nombre=EString
		public Assignment getNombreAssignment_1() { return cNombreAssignment_1; }
		
		//EString
		public RuleCall getNombreEStringParserRuleCall_1_0() { return cNombreEStringParserRuleCall_1_0; }
		
		//'(' (primaryKey?='PK,mockType' EQUAL mockType=Mockaroo | 'mockType' EQUAL mockType=Mockaroo) ')'
		public Group getGroup_2() { return cGroup_2; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2_0() { return cLeftParenthesisKeyword_2_0; }
		
		//primaryKey?='PK,mockType' EQUAL mockType=Mockaroo | 'mockType' EQUAL mockType=Mockaroo
		public Alternatives getAlternatives_2_1() { return cAlternatives_2_1; }
		
		//primaryKey?='PK,mockType' EQUAL mockType=Mockaroo
		public Group getGroup_2_1_0() { return cGroup_2_1_0; }
		
		//primaryKey?='PK,mockType'
		public Assignment getPrimaryKeyAssignment_2_1_0_0() { return cPrimaryKeyAssignment_2_1_0_0; }
		
		//'PK,mockType'
		public Keyword getPrimaryKeyPKMockTypeKeyword_2_1_0_0_0() { return cPrimaryKeyPKMockTypeKeyword_2_1_0_0_0; }
		
		//EQUAL
		public RuleCall getEQUALTerminalRuleCall_2_1_0_1() { return cEQUALTerminalRuleCall_2_1_0_1; }
		
		//mockType=Mockaroo
		public Assignment getMockTypeAssignment_2_1_0_2() { return cMockTypeAssignment_2_1_0_2; }
		
		//Mockaroo
		public RuleCall getMockTypeMockarooEnumRuleCall_2_1_0_2_0() { return cMockTypeMockarooEnumRuleCall_2_1_0_2_0; }
		
		//'mockType' EQUAL mockType=Mockaroo
		public Group getGroup_2_1_1() { return cGroup_2_1_1; }
		
		//'mockType'
		public Keyword getMockTypeKeyword_2_1_1_0() { return cMockTypeKeyword_2_1_1_0; }
		
		//EQUAL
		public RuleCall getEQUALTerminalRuleCall_2_1_1_1() { return cEQUALTerminalRuleCall_2_1_1_1; }
		
		//mockType=Mockaroo
		public Assignment getMockTypeAssignment_2_1_1_2() { return cMockTypeAssignment_2_1_1_2; }
		
		//Mockaroo
		public RuleCall getMockTypeMockarooEnumRuleCall_2_1_1_2_0() { return cMockTypeMockarooEnumRuleCall_2_1_1_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2_2() { return cRightParenthesisKeyword_2_2; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_3() { return cSEMICOLONTerminalRuleCall_3; }
	}
	public class AtributoArregloElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.AtributoArreglo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTipoAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTipoTipoAtributoEnumRuleCall_0_0 = (RuleCall)cTipoAssignment_0.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNombreAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNombreEStringParserRuleCall_3_0 = (RuleCall)cNombreAssignment_3.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//AtributoArreglo:
		//	tipo=TipoAtributo '[' ']' nombre=EString SEMICOLON;
		@Override public ParserRule getRule() { return rule; }
		
		//tipo=TipoAtributo '[' ']' nombre=EString SEMICOLON
		public Group getGroup() { return cGroup; }
		
		//tipo=TipoAtributo
		public Assignment getTipoAssignment_0() { return cTipoAssignment_0; }
		
		//TipoAtributo
		public RuleCall getTipoTipoAtributoEnumRuleCall_0_0() { return cTipoTipoAtributoEnumRuleCall_0_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_1() { return cLeftSquareBracketKeyword_1; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_2() { return cRightSquareBracketKeyword_2; }
		
		//nombre=EString
		public Assignment getNombreAssignment_3() { return cNombreAssignment_3; }
		
		//EString
		public RuleCall getNombreEStringParserRuleCall_3_0() { return cNombreEStringParserRuleCall_3_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_4() { return cSEMICOLONTerminalRuleCall_4; }
	}
	public class AtributoSimpleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.AtributoSimple");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTipoAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTipoTipoAtributoEnumRuleCall_0_0 = (RuleCall)cTipoAssignment_0.eContents().get(0);
		private final Assignment cNombreAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNombreEStringParserRuleCall_1_0 = (RuleCall)cNombreAssignment_1.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//AtributoSimple:
		//	tipo=TipoAtributo nombre=EString SEMICOLON;
		@Override public ParserRule getRule() { return rule; }
		
		//tipo=TipoAtributo nombre=EString SEMICOLON
		public Group getGroup() { return cGroup; }
		
		//tipo=TipoAtributo
		public Assignment getTipoAssignment_0() { return cTipoAssignment_0; }
		
		//TipoAtributo
		public RuleCall getTipoTipoAtributoEnumRuleCall_0_0() { return cTipoTipoAtributoEnumRuleCall_0_0; }
		
		//nombre=EString
		public Assignment getNombreAssignment_1() { return cNombreAssignment_1; }
		
		//EString
		public RuleCall getNombreEStringParserRuleCall_1_0() { return cNombreEStringParserRuleCall_1_0; }
		
		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_2() { return cSEMICOLONTerminalRuleCall_2; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class MockarooEntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.MockarooEntity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEntityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNombreAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNombreEStringParserRuleCall_1_0 = (RuleCall)cNombreAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAtributosAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAtributosAtributoParserRuleCall_3_0 = (RuleCall)cAtributosAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//MockarooEntity:
		//	'Entity' nombre=EString '{'
		//	atributos+=Atributo*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Entity' nombre=EString '{' atributos+=Atributo* '}'
		public Group getGroup() { return cGroup; }
		
		//'Entity'
		public Keyword getEntityKeyword_0() { return cEntityKeyword_0; }
		
		//nombre=EString
		public Assignment getNombreAssignment_1() { return cNombreAssignment_1; }
		
		//EString
		public RuleCall getNombreEStringParserRuleCall_1_0() { return cNombreEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//atributos+=Atributo*
		public Assignment getAtributosAssignment_3() { return cAtributosAssignment_3; }
		
		//Atributo
		public RuleCall getAtributosAtributoParserRuleCall_3_0() { return cAtributosAtributoParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ServicioRestElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ServicioRest");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cServicioRestKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cMetodoKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cMetodoAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cMetodoTipoMetodoRestEnumRuleCall_2_1_0 = (RuleCall)cMetodoAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNombreKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNombreAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNombreEStringParserRuleCall_3_1_0 = (RuleCall)cNombreAssignment_3_1.eContents().get(0);
		private final Keyword cEntidadesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cEntidadesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cEntidadesEntidadCrossReference_6_0 = (CrossReference)cEntidadesAssignment_6.eContents().get(0);
		private final RuleCall cEntidadesEntidadEStringParserRuleCall_6_0_1 = (RuleCall)cEntidadesEntidadCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cEntidadesAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cEntidadesEntidadCrossReference_7_1_0 = (CrossReference)cEntidadesAssignment_7_1.eContents().get(0);
		private final RuleCall cEntidadesEntidadEStringParserRuleCall_7_1_0_1 = (RuleCall)cEntidadesEntidadCrossReference_7_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cResponseKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cResponseAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cResponseResponseParserRuleCall_10_0 = (RuleCall)cResponseAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//ServicioRest:
		//	'ServicioRest'
		//	'{' ('metodo' metodo=TipoMetodoRest)? ('nombre' nombre=EString)?
		//	'entidades' '(' entidades+=[Entidad|EString] ("," entidades+=[Entidad|EString])* ')'
		//	'response' response=Response
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ServicioRest' '{' ('metodo' metodo=TipoMetodoRest)? ('nombre' nombre=EString)? 'entidades' '('
		//entidades+=[Entidad|EString] ("," entidades+=[Entidad|EString])* ')' 'response' response=Response '}'
		public Group getGroup() { return cGroup; }
		
		//'ServicioRest'
		public Keyword getServicioRestKeyword_0() { return cServicioRestKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('metodo' metodo=TipoMetodoRest)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'metodo'
		public Keyword getMetodoKeyword_2_0() { return cMetodoKeyword_2_0; }
		
		//metodo=TipoMetodoRest
		public Assignment getMetodoAssignment_2_1() { return cMetodoAssignment_2_1; }
		
		//TipoMetodoRest
		public RuleCall getMetodoTipoMetodoRestEnumRuleCall_2_1_0() { return cMetodoTipoMetodoRestEnumRuleCall_2_1_0; }
		
		//('nombre' nombre=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'nombre'
		public Keyword getNombreKeyword_3_0() { return cNombreKeyword_3_0; }
		
		//nombre=EString
		public Assignment getNombreAssignment_3_1() { return cNombreAssignment_3_1; }
		
		//EString
		public RuleCall getNombreEStringParserRuleCall_3_1_0() { return cNombreEStringParserRuleCall_3_1_0; }
		
		//'entidades'
		public Keyword getEntidadesKeyword_4() { return cEntidadesKeyword_4; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5() { return cLeftParenthesisKeyword_5; }
		
		//entidades+=[Entidad|EString]
		public Assignment getEntidadesAssignment_6() { return cEntidadesAssignment_6; }
		
		//[Entidad|EString]
		public CrossReference getEntidadesEntidadCrossReference_6_0() { return cEntidadesEntidadCrossReference_6_0; }
		
		//EString
		public RuleCall getEntidadesEntidadEStringParserRuleCall_6_0_1() { return cEntidadesEntidadEStringParserRuleCall_6_0_1; }
		
		//("," entidades+=[Entidad|EString])*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//entidades+=[Entidad|EString]
		public Assignment getEntidadesAssignment_7_1() { return cEntidadesAssignment_7_1; }
		
		//[Entidad|EString]
		public CrossReference getEntidadesEntidadCrossReference_7_1_0() { return cEntidadesEntidadCrossReference_7_1_0; }
		
		//EString
		public RuleCall getEntidadesEntidadEStringParserRuleCall_7_1_0_1() { return cEntidadesEntidadEStringParserRuleCall_7_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_8() { return cRightParenthesisKeyword_8; }
		
		//'response'
		public Keyword getResponseKeyword_9() { return cResponseKeyword_9; }
		
		//response=Response
		public Assignment getResponseAssignment_10() { return cResponseAssignment_10; }
		
		//Response
		public RuleCall getResponseResponseParserRuleCall_10_0() { return cResponseResponseParserRuleCall_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class TestElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Test");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTestKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cDescripcionKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cDescripcionAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cDescripcionEStringParserRuleCall_2_1_0 = (RuleCall)cDescripcionAssignment_2_1.eContents().get(0);
		private final Keyword cServiceKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cServiceAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cServiceServicioRestCrossReference_4_0 = (CrossReference)cServiceAssignment_4.eContents().get(0);
		private final RuleCall cServiceServicioRestEStringParserRuleCall_4_0_1 = (RuleCall)cServiceServicioRestCrossReference_4_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cMappingsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cMappingsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cMappingsMappingParserRuleCall_5_2_0 = (RuleCall)cMappingsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cMappingsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cMappingsMappingParserRuleCall_5_3_1_0 = (RuleCall)cMappingsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cAsertionsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cAsertionsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cAsertionsAsercionParserRuleCall_6_2_0 = (RuleCall)cAsertionsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cAsertionsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cAsertionsAsercionParserRuleCall_6_3_1_0 = (RuleCall)cAsertionsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Test:
		//	'Test'
		//	'{' ('descripcion' descripcion=EString)?
		//	'service' service=[ServicioRest|EString] ('mappings' '{' mappings+=Mapping ("," mappings+=Mapping)* '}')?
		//	('asertions' '{' asertions+=Asercion ("," asertions+=Asercion)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Test' '{' ('descripcion' descripcion=EString)? 'service' service=[ServicioRest|EString] ('mappings' '{'
		//mappings+=Mapping ("," mappings+=Mapping)* '}')? ('asertions' '{' asertions+=Asercion ("," asertions+=Asercion)* '}')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Test'
		public Keyword getTestKeyword_0() { return cTestKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('descripcion' descripcion=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'descripcion'
		public Keyword getDescripcionKeyword_2_0() { return cDescripcionKeyword_2_0; }
		
		//descripcion=EString
		public Assignment getDescripcionAssignment_2_1() { return cDescripcionAssignment_2_1; }
		
		//EString
		public RuleCall getDescripcionEStringParserRuleCall_2_1_0() { return cDescripcionEStringParserRuleCall_2_1_0; }
		
		//'service'
		public Keyword getServiceKeyword_3() { return cServiceKeyword_3; }
		
		//service=[ServicioRest|EString]
		public Assignment getServiceAssignment_4() { return cServiceAssignment_4; }
		
		//[ServicioRest|EString]
		public CrossReference getServiceServicioRestCrossReference_4_0() { return cServiceServicioRestCrossReference_4_0; }
		
		//EString
		public RuleCall getServiceServicioRestEStringParserRuleCall_4_0_1() { return cServiceServicioRestEStringParserRuleCall_4_0_1; }
		
		//('mappings' '{' mappings+=Mapping ("," mappings+=Mapping)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'mappings'
		public Keyword getMappingsKeyword_5_0() { return cMappingsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//mappings+=Mapping
		public Assignment getMappingsAssignment_5_2() { return cMappingsAssignment_5_2; }
		
		//Mapping
		public RuleCall getMappingsMappingParserRuleCall_5_2_0() { return cMappingsMappingParserRuleCall_5_2_0; }
		
		//("," mappings+=Mapping)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//mappings+=Mapping
		public Assignment getMappingsAssignment_5_3_1() { return cMappingsAssignment_5_3_1; }
		
		//Mapping
		public RuleCall getMappingsMappingParserRuleCall_5_3_1_0() { return cMappingsMappingParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//('asertions' '{' asertions+=Asercion ("," asertions+=Asercion)* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'asertions'
		public Keyword getAsertionsKeyword_6_0() { return cAsertionsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//asertions+=Asercion
		public Assignment getAsertionsAssignment_6_2() { return cAsertionsAssignment_6_2; }
		
		//Asercion
		public RuleCall getAsertionsAsercionParserRuleCall_6_2_0() { return cAsertionsAsercionParserRuleCall_6_2_0; }
		
		//("," asertions+=Asercion)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//asertions+=Asercion
		public Assignment getAsertionsAssignment_6_3_1() { return cAsertionsAssignment_6_3_1; }
		
		//Asercion
		public RuleCall getAsertionsAsercionParserRuleCall_6_3_1_0() { return cAsertionsAsercionParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class SimpleEntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SimpleEntity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSimpleEntityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNombreAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNombreEStringParserRuleCall_1_0 = (RuleCall)cNombreAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAtributosAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAtributosAtributoSimpleParserRuleCall_3_0 = (RuleCall)cAtributosAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//SimpleEntity:
		//	'SimpleEntity' nombre=EString '{'
		//	atributos+=AtributoSimple*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'SimpleEntity' nombre=EString '{' atributos+=AtributoSimple* '}'
		public Group getGroup() { return cGroup; }
		
		//'SimpleEntity'
		public Keyword getSimpleEntityKeyword_0() { return cSimpleEntityKeyword_0; }
		
		//nombre=EString
		public Assignment getNombreAssignment_1() { return cNombreAssignment_1; }
		
		//EString
		public RuleCall getNombreEStringParserRuleCall_1_0() { return cNombreEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//atributos+=AtributoSimple*
		public Assignment getAtributosAssignment_3() { return cAtributosAssignment_3; }
		
		//AtributoSimple
		public RuleCall getAtributosAtributoSimpleParserRuleCall_3_0() { return cAtributosAtributoSimpleParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class MyNumericElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.MyNumeric");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMyNumericAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMyNumericKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cValorKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValorAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValorEDoubleParserRuleCall_3_1_0 = (RuleCall)cValorAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//MyNumeric:
		//	{MyNumeric}
		//	'MyNumeric'
		//	'{' ('valor' valor=EDouble)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{MyNumeric} 'MyNumeric' '{' ('valor' valor=EDouble)? '}'
		public Group getGroup() { return cGroup; }
		
		//{MyNumeric}
		public Action getMyNumericAction_0() { return cMyNumericAction_0; }
		
		//'MyNumeric'
		public Keyword getMyNumericKeyword_1() { return cMyNumericKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('valor' valor=EDouble)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'valor'
		public Keyword getValorKeyword_3_0() { return cValorKeyword_3_0; }
		
		//valor=EDouble
		public Assignment getValorAssignment_3_1() { return cValorAssignment_3_1; }
		
		//EDouble
		public RuleCall getValorEDoubleParserRuleCall_3_1_0() { return cValorEDoubleParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class MyStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.MyString");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMyStringAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMyStringKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cValorKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValorAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValorEStringParserRuleCall_3_1_0 = (RuleCall)cValorAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//MyString:
		//	{MyString}
		//	'MyString'
		//	'{' ('valor' valor=EString)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{MyString} 'MyString' '{' ('valor' valor=EString)? '}'
		public Group getGroup() { return cGroup; }
		
		//{MyString}
		public Action getMyStringAction_0() { return cMyStringAction_0; }
		
		//'MyString'
		public Keyword getMyStringKeyword_1() { return cMyStringKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('valor' valor=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'valor'
		public Keyword getValorKeyword_3_0() { return cValorKeyword_3_0; }
		
		//valor=EString
		public Assignment getValorAssignment_3_1() { return cValorAssignment_3_1; }
		
		//EString
		public RuleCall getValorEStringParserRuleCall_3_1_0() { return cValorEStringParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class MyBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.MyBoolean");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMyBooleanAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cValorAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cValorValorKeyword_1_0 = (Keyword)cValorAssignment_1.eContents().get(0);
		private final Keyword cMyBooleanKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//MyBoolean:
		//	{MyBoolean} valor?='valor'?
		//	'MyBoolean';
		@Override public ParserRule getRule() { return rule; }
		
		//{MyBoolean} valor?='valor'? 'MyBoolean'
		public Group getGroup() { return cGroup; }
		
		//{MyBoolean}
		public Action getMyBooleanAction_0() { return cMyBooleanAction_0; }
		
		//valor?='valor'?
		public Assignment getValorAssignment_1() { return cValorAssignment_1; }
		
		//'valor'
		public Keyword getValorValorKeyword_1_0() { return cValorValorKeyword_1_0; }
		
		//'MyBoolean'
		public Keyword getMyBooleanKeyword_2() { return cMyBooleanKeyword_2; }
	}
	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EDouble ecore::EDouble:
		//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E' | 'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E' | 'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'E' | 'e'
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class ResponseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Response");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cResponseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cAtributosKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cAtributosAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cAtributosAtributoParserRuleCall_4_0 = (RuleCall)cAtributosAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cAtributosAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cAtributosAtributoParserRuleCall_5_1_0 = (RuleCall)cAtributosAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Response:
		//	'Response'
		//	'{'
		//	'atributos' '{' atributos+=Atributo ("," atributos+=Atributo)* '}'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Response' '{' 'atributos' '{' atributos+=Atributo ("," atributos+=Atributo)* '}' '}'
		public Group getGroup() { return cGroup; }
		
		//'Response'
		public Keyword getResponseKeyword_0() { return cResponseKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'atributos'
		public Keyword getAtributosKeyword_2() { return cAtributosKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//atributos+=Atributo
		public Assignment getAtributosAssignment_4() { return cAtributosAssignment_4; }
		
		//Atributo
		public RuleCall getAtributosAtributoParserRuleCall_4_0() { return cAtributosAtributoParserRuleCall_4_0; }
		
		//("," atributos+=Atributo)*
		public Group getGroup_5() { return cGroup_5; }
		
		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//atributos+=Atributo
		public Assignment getAtributosAssignment_5_1() { return cAtributosAssignment_5_1; }
		
		//Atributo
		public RuleCall getAtributosAtributoParserRuleCall_5_1_0() { return cAtributosAtributoParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class MappingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Mapping");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMappingKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cValueKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cValueAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cValueElementoCrossReference_3_0 = (CrossReference)cValueAssignment_3.eContents().get(0);
		private final RuleCall cValueElementoEStringParserRuleCall_3_0_1 = (RuleCall)cValueElementoCrossReference_3_0.eContents().get(1);
		private final Keyword cParametroKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cParametroAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cParametroParametroParserRuleCall_5_0 = (RuleCall)cParametroAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Mapping:
		//	'Mapping'
		//	'{'
		//	'value' value=[Elemento|EString]
		//	'parametro' parametro=Parametro
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Mapping' '{' 'value' value=[Elemento|EString] 'parametro' parametro=Parametro '}'
		public Group getGroup() { return cGroup; }
		
		//'Mapping'
		public Keyword getMappingKeyword_0() { return cMappingKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'value'
		public Keyword getValueKeyword_2() { return cValueKeyword_2; }
		
		//value=[Elemento|EString]
		public Assignment getValueAssignment_3() { return cValueAssignment_3; }
		
		//[Elemento|EString]
		public CrossReference getValueElementoCrossReference_3_0() { return cValueElementoCrossReference_3_0; }
		
		//EString
		public RuleCall getValueElementoEStringParserRuleCall_3_0_1() { return cValueElementoEStringParserRuleCall_3_0_1; }
		
		//'parametro'
		public Keyword getParametroKeyword_4() { return cParametroKeyword_4; }
		
		//parametro=Parametro
		public Assignment getParametroAssignment_5() { return cParametroAssignment_5; }
		
		//Parametro
		public RuleCall getParametroParametroParserRuleCall_5_0() { return cParametroParametroParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class AsercionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Asercion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAsercionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cElemento1Keyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cElemento1Assignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cElemento1ElementoCrossReference_3_0 = (CrossReference)cElemento1Assignment_3.eContents().get(0);
		private final RuleCall cElemento1ElementoEStringParserRuleCall_3_0_1 = (RuleCall)cElemento1ElementoCrossReference_3_0.eContents().get(1);
		private final Keyword cElemento2Keyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cElemento2Assignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cElemento2ElementoCrossReference_5_0 = (CrossReference)cElemento2Assignment_5.eContents().get(0);
		private final RuleCall cElemento2ElementoEStringParserRuleCall_5_0_1 = (RuleCall)cElemento2ElementoCrossReference_5_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Asercion:
		//	'Asercion'
		//	'{'
		//	'elemento1' elemento1=[Elemento|EString]
		//	'elemento2' elemento2=[Elemento|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Asercion' '{' 'elemento1' elemento1=[Elemento|EString] 'elemento2' elemento2=[Elemento|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//'Asercion'
		public Keyword getAsercionKeyword_0() { return cAsercionKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'elemento1'
		public Keyword getElemento1Keyword_2() { return cElemento1Keyword_2; }
		
		//elemento1=[Elemento|EString]
		public Assignment getElemento1Assignment_3() { return cElemento1Assignment_3; }
		
		//[Elemento|EString]
		public CrossReference getElemento1ElementoCrossReference_3_0() { return cElemento1ElementoCrossReference_3_0; }
		
		//EString
		public RuleCall getElemento1ElementoEStringParserRuleCall_3_0_1() { return cElemento1ElementoEStringParserRuleCall_3_0_1; }
		
		//'elemento2'
		public Keyword getElemento2Keyword_4() { return cElemento2Keyword_4; }
		
		//elemento2=[Elemento|EString]
		public Assignment getElemento2Assignment_5() { return cElemento2Assignment_5; }
		
		//[Elemento|EString]
		public CrossReference getElemento2ElementoCrossReference_5_0() { return cElemento2ElementoCrossReference_5_0; }
		
		//EString
		public RuleCall getElemento2ElementoEStringParserRuleCall_5_0_1() { return cElemento2ElementoEStringParserRuleCall_5_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ParametroElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Parametro");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cParametroAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cParametroKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNombreKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNombreAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNombreEStringParserRuleCall_3_1_0 = (RuleCall)cNombreAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTipoKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTipoAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTipoTipoParametroEnumRuleCall_4_1_0 = (RuleCall)cTipoAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Parametro:
		//	{Parametro}
		//	'Parametro'
		//	'{' ('nombre' nombre=EString)? ('tipo' tipo=TipoParametro)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Parametro} 'Parametro' '{' ('nombre' nombre=EString)? ('tipo' tipo=TipoParametro)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Parametro}
		public Action getParametroAction_0() { return cParametroAction_0; }
		
		//'Parametro'
		public Keyword getParametroKeyword_1() { return cParametroKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('nombre' nombre=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'nombre'
		public Keyword getNombreKeyword_3_0() { return cNombreKeyword_3_0; }
		
		//nombre=EString
		public Assignment getNombreAssignment_3_1() { return cNombreAssignment_3_1; }
		
		//EString
		public RuleCall getNombreEStringParserRuleCall_3_1_0() { return cNombreEStringParserRuleCall_3_1_0; }
		
		//('tipo' tipo=TipoParametro)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'tipo'
		public Keyword getTipoKeyword_4_0() { return cTipoKeyword_4_0; }
		
		//tipo=TipoParametro
		public Assignment getTipoAssignment_4_1() { return cTipoAssignment_4_1; }
		
		//TipoParametro
		public RuleCall getTipoTipoParametroEnumRuleCall_4_1_0() { return cTipoTipoParametroEnumRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	public class TipoAtributoElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.TipoAtributo");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cStringEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cStringStringKeyword_0_0 = (Keyword)cStringEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cIntEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cIntIntKeyword_1_0 = (Keyword)cIntEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBooleanEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBooleanBooleanKeyword_2_0 = (Keyword)cBooleanEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum TipoAtributo:
		//	string | int | boolean;
		public EnumRule getRule() { return rule; }
		
		//string | int | boolean
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//string
		public EnumLiteralDeclaration getStringEnumLiteralDeclaration_0() { return cStringEnumLiteralDeclaration_0; }
		
		//'string'
		public Keyword getStringStringKeyword_0_0() { return cStringStringKeyword_0_0; }
		
		//int
		public EnumLiteralDeclaration getIntEnumLiteralDeclaration_1() { return cIntEnumLiteralDeclaration_1; }
		
		//'int'
		public Keyword getIntIntKeyword_1_0() { return cIntIntKeyword_1_0; }
		
		//boolean
		public EnumLiteralDeclaration getBooleanEnumLiteralDeclaration_2() { return cBooleanEnumLiteralDeclaration_2; }
		
		//'boolean'
		public Keyword getBooleanBooleanKeyword_2_0() { return cBooleanBooleanKeyword_2_0; }
	}
	public class MockarooElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Mockaroo");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cFirstNameTypeEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cFirstNameTypeFirstNameTypeKeyword_0_0 = (Keyword)cFirstNameTypeEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cLastNameTypeEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cLastNameTypeLastNameTypeKeyword_1_0 = (Keyword)cLastNameTypeEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cFamilyNameTypeEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cFamilyNameTypeFamilyNameTypeKeyword_2_0 = (Keyword)cFamilyNameTypeEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cFullNameTypeEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cFullNameTypeFullNameTypeKeyword_3_0 = (Keyword)cFullNameTypeEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cGenderTypeEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cGenderTypeGenderTypeKeyword_4_0 = (Keyword)cGenderTypeEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cEmailAddressTypeEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cEmailAddressTypeEmailAddressTypeKeyword_5_0 = (Keyword)cEmailAddressTypeEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cPhoneTypeEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cPhoneTypePhoneTypeKeyword_6_0 = (Keyword)cPhoneTypeEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cCountryTypeEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cCountryTypeCountryTypeKeyword_7_0 = (Keyword)cCountryTypeEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cCityTypeEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cCityTypeCityTypeKeyword_8_0 = (Keyword)cCityTypeEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cCountryCodeTypeEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cCountryCodeTypeCountryCodeTypeKeyword_9_0 = (Keyword)cCountryCodeTypeEnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cLatitudeTypeEnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cLatitudeTypeLatitudeTypeKeyword_10_0 = (Keyword)cLatitudeTypeEnumLiteralDeclaration_10.eContents().get(0);
		private final EnumLiteralDeclaration cLongitudTypeEnumLiteralDeclaration_11 = (EnumLiteralDeclaration)cAlternatives.eContents().get(11);
		private final Keyword cLongitudTypeLongitudTypeKeyword_11_0 = (Keyword)cLongitudTypeEnumLiteralDeclaration_11.eContents().get(0);
		private final EnumLiteralDeclaration cRowNumberTypeEnumLiteralDeclaration_12 = (EnumLiteralDeclaration)cAlternatives.eContents().get(12);
		private final Keyword cRowNumberTypeRowNumberTypeKeyword_12_0 = (Keyword)cRowNumberTypeEnumLiteralDeclaration_12.eContents().get(0);
		private final EnumLiteralDeclaration cBooleanTypeEnumLiteralDeclaration_13 = (EnumLiteralDeclaration)cAlternatives.eContents().get(13);
		private final Keyword cBooleanTypeBooleanTypeKeyword_13_0 = (Keyword)cBooleanTypeEnumLiteralDeclaration_13.eContents().get(0);
		
		//enum Mockaroo:
		//	FirstNameType | LastNameType | FamilyNameType | FullNameType | GenderType | EmailAddressType | PhoneType |
		//	CountryType | CityType | CountryCodeType | LatitudeType | LongitudType | RowNumberType | BooleanType;
		public EnumRule getRule() { return rule; }
		
		//FirstNameType | LastNameType | FamilyNameType | FullNameType | GenderType | EmailAddressType | PhoneType | CountryType |
		//CityType | CountryCodeType | LatitudeType | LongitudType | RowNumberType | BooleanType
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FirstNameType
		public EnumLiteralDeclaration getFirstNameTypeEnumLiteralDeclaration_0() { return cFirstNameTypeEnumLiteralDeclaration_0; }
		
		//'FirstNameType'
		public Keyword getFirstNameTypeFirstNameTypeKeyword_0_0() { return cFirstNameTypeFirstNameTypeKeyword_0_0; }
		
		//LastNameType
		public EnumLiteralDeclaration getLastNameTypeEnumLiteralDeclaration_1() { return cLastNameTypeEnumLiteralDeclaration_1; }
		
		//'LastNameType'
		public Keyword getLastNameTypeLastNameTypeKeyword_1_0() { return cLastNameTypeLastNameTypeKeyword_1_0; }
		
		//FamilyNameType
		public EnumLiteralDeclaration getFamilyNameTypeEnumLiteralDeclaration_2() { return cFamilyNameTypeEnumLiteralDeclaration_2; }
		
		//'FamilyNameType'
		public Keyword getFamilyNameTypeFamilyNameTypeKeyword_2_0() { return cFamilyNameTypeFamilyNameTypeKeyword_2_0; }
		
		//FullNameType
		public EnumLiteralDeclaration getFullNameTypeEnumLiteralDeclaration_3() { return cFullNameTypeEnumLiteralDeclaration_3; }
		
		//'FullNameType'
		public Keyword getFullNameTypeFullNameTypeKeyword_3_0() { return cFullNameTypeFullNameTypeKeyword_3_0; }
		
		//GenderType
		public EnumLiteralDeclaration getGenderTypeEnumLiteralDeclaration_4() { return cGenderTypeEnumLiteralDeclaration_4; }
		
		//'GenderType'
		public Keyword getGenderTypeGenderTypeKeyword_4_0() { return cGenderTypeGenderTypeKeyword_4_0; }
		
		//EmailAddressType
		public EnumLiteralDeclaration getEmailAddressTypeEnumLiteralDeclaration_5() { return cEmailAddressTypeEnumLiteralDeclaration_5; }
		
		//'EmailAddressType'
		public Keyword getEmailAddressTypeEmailAddressTypeKeyword_5_0() { return cEmailAddressTypeEmailAddressTypeKeyword_5_0; }
		
		//PhoneType
		public EnumLiteralDeclaration getPhoneTypeEnumLiteralDeclaration_6() { return cPhoneTypeEnumLiteralDeclaration_6; }
		
		//'PhoneType'
		public Keyword getPhoneTypePhoneTypeKeyword_6_0() { return cPhoneTypePhoneTypeKeyword_6_0; }
		
		//CountryType
		public EnumLiteralDeclaration getCountryTypeEnumLiteralDeclaration_7() { return cCountryTypeEnumLiteralDeclaration_7; }
		
		//'CountryType'
		public Keyword getCountryTypeCountryTypeKeyword_7_0() { return cCountryTypeCountryTypeKeyword_7_0; }
		
		//CityType
		public EnumLiteralDeclaration getCityTypeEnumLiteralDeclaration_8() { return cCityTypeEnumLiteralDeclaration_8; }
		
		//'CityType'
		public Keyword getCityTypeCityTypeKeyword_8_0() { return cCityTypeCityTypeKeyword_8_0; }
		
		//CountryCodeType
		public EnumLiteralDeclaration getCountryCodeTypeEnumLiteralDeclaration_9() { return cCountryCodeTypeEnumLiteralDeclaration_9; }
		
		//'CountryCodeType'
		public Keyword getCountryCodeTypeCountryCodeTypeKeyword_9_0() { return cCountryCodeTypeCountryCodeTypeKeyword_9_0; }
		
		//LatitudeType
		public EnumLiteralDeclaration getLatitudeTypeEnumLiteralDeclaration_10() { return cLatitudeTypeEnumLiteralDeclaration_10; }
		
		//'LatitudeType'
		public Keyword getLatitudeTypeLatitudeTypeKeyword_10_0() { return cLatitudeTypeLatitudeTypeKeyword_10_0; }
		
		//LongitudType
		public EnumLiteralDeclaration getLongitudTypeEnumLiteralDeclaration_11() { return cLongitudTypeEnumLiteralDeclaration_11; }
		
		//'LongitudType'
		public Keyword getLongitudTypeLongitudTypeKeyword_11_0() { return cLongitudTypeLongitudTypeKeyword_11_0; }
		
		//RowNumberType
		public EnumLiteralDeclaration getRowNumberTypeEnumLiteralDeclaration_12() { return cRowNumberTypeEnumLiteralDeclaration_12; }
		
		//'RowNumberType'
		public Keyword getRowNumberTypeRowNumberTypeKeyword_12_0() { return cRowNumberTypeRowNumberTypeKeyword_12_0; }
		
		//BooleanType
		public EnumLiteralDeclaration getBooleanTypeEnumLiteralDeclaration_13() { return cBooleanTypeEnumLiteralDeclaration_13; }
		
		//'BooleanType'
		public Keyword getBooleanTypeBooleanTypeKeyword_13_0() { return cBooleanTypeBooleanTypeKeyword_13_0; }
	}
	public class TipoMetodoRestElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.TipoMetodoRest");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cGETEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cGETGETKeyword_0_0 = (Keyword)cGETEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPOSTEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPOSTPOSTKeyword_1_0 = (Keyword)cPOSTEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cPUTEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cPUTPUTKeyword_2_0 = (Keyword)cPUTEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDELETEEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDELETEDELETEKeyword_3_0 = (Keyword)cDELETEEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum TipoMetodoRest:
		//	GET | POST | PUT | DELETE;
		public EnumRule getRule() { return rule; }
		
		//GET | POST | PUT | DELETE
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//GET
		public EnumLiteralDeclaration getGETEnumLiteralDeclaration_0() { return cGETEnumLiteralDeclaration_0; }
		
		//'GET'
		public Keyword getGETGETKeyword_0_0() { return cGETGETKeyword_0_0; }
		
		//POST
		public EnumLiteralDeclaration getPOSTEnumLiteralDeclaration_1() { return cPOSTEnumLiteralDeclaration_1; }
		
		//'POST'
		public Keyword getPOSTPOSTKeyword_1_0() { return cPOSTPOSTKeyword_1_0; }
		
		//PUT
		public EnumLiteralDeclaration getPUTEnumLiteralDeclaration_2() { return cPUTEnumLiteralDeclaration_2; }
		
		//'PUT'
		public Keyword getPUTPUTKeyword_2_0() { return cPUTPUTKeyword_2_0; }
		
		//DELETE
		public EnumLiteralDeclaration getDELETEEnumLiteralDeclaration_3() { return cDELETEEnumLiteralDeclaration_3; }
		
		//'DELETE'
		public Keyword getDELETEDELETEKeyword_3_0() { return cDELETEDELETEKeyword_3_0; }
	}
	public class TipoParametroElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.TipoParametro");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPathEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPathPathKeyword_0_0 = (Keyword)cPathEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cQueryEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cQueryQueryKeyword_1_0 = (Keyword)cQueryEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBodyEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBodyBodyKeyword_2_0 = (Keyword)cBodyEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum TipoParametro:
		//	Path | Query | Body;
		public EnumRule getRule() { return rule; }
		
		//Path | Query | Body
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Path
		public EnumLiteralDeclaration getPathEnumLiteralDeclaration_0() { return cPathEnumLiteralDeclaration_0; }
		
		//'Path'
		public Keyword getPathPathKeyword_0_0() { return cPathPathKeyword_0_0; }
		
		//Query
		public EnumLiteralDeclaration getQueryEnumLiteralDeclaration_1() { return cQueryEnumLiteralDeclaration_1; }
		
		//'Query'
		public Keyword getQueryQueryKeyword_1_0() { return cQueryQueryKeyword_1_0; }
		
		//Body
		public EnumLiteralDeclaration getBodyEnumLiteralDeclaration_2() { return cBodyEnumLiteralDeclaration_2; }
		
		//'Body'
		public Keyword getBodyBodyKeyword_2_0() { return cBodyBodyKeyword_2_0; }
	}
	
	private final ApiElements pApi;
	private final EntidadElements pEntidad;
	private final PrimitiveTypeElements pPrimitiveType;
	private final AtributoElements pAtributo;
	private final AtributoMockaElements pAtributoMocka;
	private final AtributoArregloElements pAtributoArreglo;
	private final AtributoSimpleElements pAtributoSimple;
	private final EStringElements pEString;
	private final MockarooEntityElements pMockarooEntity;
	private final ServicioRestElements pServicioRest;
	private final TestElements pTest;
	private final SimpleEntityElements pSimpleEntity;
	private final EBooleanElements pEBoolean;
	private final TipoAtributoElements eTipoAtributo;
	private final MockarooElements eMockaroo;
	private final MyNumericElements pMyNumeric;
	private final MyStringElements pMyString;
	private final MyBooleanElements pMyBoolean;
	private final EDoubleElements pEDouble;
	private final TipoMetodoRestElements eTipoMetodoRest;
	private final ResponseElements pResponse;
	private final MappingElements pMapping;
	private final AsercionElements pAsercion;
	private final ParametroElements pParametro;
	private final TipoParametroElements eTipoParametro;
	private final TerminalRule tEQUAL;
	private final TerminalRule tSEMICOLON;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pApi = new ApiElements();
		this.pEntidad = new EntidadElements();
		this.pPrimitiveType = new PrimitiveTypeElements();
		this.pAtributo = new AtributoElements();
		this.pAtributoMocka = new AtributoMockaElements();
		this.pAtributoArreglo = new AtributoArregloElements();
		this.pAtributoSimple = new AtributoSimpleElements();
		this.pEString = new EStringElements();
		this.pMockarooEntity = new MockarooEntityElements();
		this.pServicioRest = new ServicioRestElements();
		this.pTest = new TestElements();
		this.pSimpleEntity = new SimpleEntityElements();
		this.pEBoolean = new EBooleanElements();
		this.eTipoAtributo = new TipoAtributoElements();
		this.eMockaroo = new MockarooElements();
		this.pMyNumeric = new MyNumericElements();
		this.pMyString = new MyStringElements();
		this.pMyBoolean = new MyBooleanElements();
		this.pEDouble = new EDoubleElements();
		this.eTipoMetodoRest = new TipoMetodoRestElements();
		this.pResponse = new ResponseElements();
		this.pMapping = new MappingElements();
		this.pAsercion = new AsercionElements();
		this.pParametro = new ParametroElements();
		this.eTipoParametro = new TipoParametroElements();
		this.tEQUAL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EQUAL");
		this.tSEMICOLON = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SEMICOLON");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Api:
	//	{Api}
	//	'apiURL' EQUAL url=EString SEMICOLON
	//	entidades+=Entidad*
	//	/**primitivetypes+=PrimitiveType
	//		serviciosRest+=ServicioRest
	//		tests+=Test**/;
	public ApiElements getApiAccess() {
		return pApi;
	}
	
	public ParserRule getApiRule() {
		return getApiAccess().getRule();
	}
	
	//Entidad:
	//	SimpleEntity | MockarooEntity;
	public EntidadElements getEntidadAccess() {
		return pEntidad;
	}
	
	public ParserRule getEntidadRule() {
		return getEntidadAccess().getRule();
	}
	
	//PrimitiveType:
	//	MyNumeric | MyString | MyBoolean;
	public PrimitiveTypeElements getPrimitiveTypeAccess() {
		return pPrimitiveType;
	}
	
	public ParserRule getPrimitiveTypeRule() {
		return getPrimitiveTypeAccess().getRule();
	}
	
	//Atributo:
	//	AtributoMocka | AtributoArreglo | AtributoSimple;
	public AtributoElements getAtributoAccess() {
		return pAtributo;
	}
	
	public ParserRule getAtributoRule() {
		return getAtributoAccess().getRule();
	}
	
	//AtributoMocka:
	//	tipo=TipoAtributo nombre=EString ('(' (primaryKey?='PK,mockType' EQUAL mockType=Mockaroo | 'mockType' EQUAL
	//	mockType=Mockaroo) ')') SEMICOLON;
	public AtributoMockaElements getAtributoMockaAccess() {
		return pAtributoMocka;
	}
	
	public ParserRule getAtributoMockaRule() {
		return getAtributoMockaAccess().getRule();
	}
	
	//AtributoArreglo:
	//	tipo=TipoAtributo '[' ']' nombre=EString SEMICOLON;
	public AtributoArregloElements getAtributoArregloAccess() {
		return pAtributoArreglo;
	}
	
	public ParserRule getAtributoArregloRule() {
		return getAtributoArregloAccess().getRule();
	}
	
	//AtributoSimple:
	//	tipo=TipoAtributo nombre=EString SEMICOLON;
	public AtributoSimpleElements getAtributoSimpleAccess() {
		return pAtributoSimple;
	}
	
	public ParserRule getAtributoSimpleRule() {
		return getAtributoSimpleAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//MockarooEntity:
	//	'Entity' nombre=EString '{'
	//	atributos+=Atributo*
	//	'}';
	public MockarooEntityElements getMockarooEntityAccess() {
		return pMockarooEntity;
	}
	
	public ParserRule getMockarooEntityRule() {
		return getMockarooEntityAccess().getRule();
	}
	
	//ServicioRest:
	//	'ServicioRest'
	//	'{' ('metodo' metodo=TipoMetodoRest)? ('nombre' nombre=EString)?
	//	'entidades' '(' entidades+=[Entidad|EString] ("," entidades+=[Entidad|EString])* ')'
	//	'response' response=Response
	//	'}';
	public ServicioRestElements getServicioRestAccess() {
		return pServicioRest;
	}
	
	public ParserRule getServicioRestRule() {
		return getServicioRestAccess().getRule();
	}
	
	//Test:
	//	'Test'
	//	'{' ('descripcion' descripcion=EString)?
	//	'service' service=[ServicioRest|EString] ('mappings' '{' mappings+=Mapping ("," mappings+=Mapping)* '}')?
	//	('asertions' '{' asertions+=Asercion ("," asertions+=Asercion)* '}')?
	//	'}';
	public TestElements getTestAccess() {
		return pTest;
	}
	
	public ParserRule getTestRule() {
		return getTestAccess().getRule();
	}
	
	//SimpleEntity:
	//	'SimpleEntity' nombre=EString '{'
	//	atributos+=AtributoSimple*
	//	'}';
	public SimpleEntityElements getSimpleEntityAccess() {
		return pSimpleEntity;
	}
	
	public ParserRule getSimpleEntityRule() {
		return getSimpleEntityAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//enum TipoAtributo:
	//	string | int | boolean;
	public TipoAtributoElements getTipoAtributoAccess() {
		return eTipoAtributo;
	}
	
	public EnumRule getTipoAtributoRule() {
		return getTipoAtributoAccess().getRule();
	}
	
	//enum Mockaroo:
	//	FirstNameType | LastNameType | FamilyNameType | FullNameType | GenderType | EmailAddressType | PhoneType |
	//	CountryType | CityType | CountryCodeType | LatitudeType | LongitudType | RowNumberType | BooleanType;
	public MockarooElements getMockarooAccess() {
		return eMockaroo;
	}
	
	public EnumRule getMockarooRule() {
		return getMockarooAccess().getRule();
	}
	
	//MyNumeric:
	//	{MyNumeric}
	//	'MyNumeric'
	//	'{' ('valor' valor=EDouble)?
	//	'}';
	public MyNumericElements getMyNumericAccess() {
		return pMyNumeric;
	}
	
	public ParserRule getMyNumericRule() {
		return getMyNumericAccess().getRule();
	}
	
	//MyString:
	//	{MyString}
	//	'MyString'
	//	'{' ('valor' valor=EString)?
	//	'}';
	public MyStringElements getMyStringAccess() {
		return pMyString;
	}
	
	public ParserRule getMyStringRule() {
		return getMyStringAccess().getRule();
	}
	
	//MyBoolean:
	//	{MyBoolean} valor?='valor'?
	//	'MyBoolean';
	public MyBooleanElements getMyBooleanAccess() {
		return pMyBoolean;
	}
	
	public ParserRule getMyBooleanRule() {
		return getMyBooleanAccess().getRule();
	}
	
	//EDouble ecore::EDouble:
	//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?;
	public EDoubleElements getEDoubleAccess() {
		return pEDouble;
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}
	
	//enum TipoMetodoRest:
	//	GET | POST | PUT | DELETE;
	public TipoMetodoRestElements getTipoMetodoRestAccess() {
		return eTipoMetodoRest;
	}
	
	public EnumRule getTipoMetodoRestRule() {
		return getTipoMetodoRestAccess().getRule();
	}
	
	//Response:
	//	'Response'
	//	'{'
	//	'atributos' '{' atributos+=Atributo ("," atributos+=Atributo)* '}'
	//	'}';
	public ResponseElements getResponseAccess() {
		return pResponse;
	}
	
	public ParserRule getResponseRule() {
		return getResponseAccess().getRule();
	}
	
	//Mapping:
	//	'Mapping'
	//	'{'
	//	'value' value=[Elemento|EString]
	//	'parametro' parametro=Parametro
	//	'}';
	public MappingElements getMappingAccess() {
		return pMapping;
	}
	
	public ParserRule getMappingRule() {
		return getMappingAccess().getRule();
	}
	
	//Asercion:
	//	'Asercion'
	//	'{'
	//	'elemento1' elemento1=[Elemento|EString]
	//	'elemento2' elemento2=[Elemento|EString]
	//	'}';
	public AsercionElements getAsercionAccess() {
		return pAsercion;
	}
	
	public ParserRule getAsercionRule() {
		return getAsercionAccess().getRule();
	}
	
	//Parametro:
	//	{Parametro}
	//	'Parametro'
	//	'{' ('nombre' nombre=EString)? ('tipo' tipo=TipoParametro)?
	//	'}';
	public ParametroElements getParametroAccess() {
		return pParametro;
	}
	
	public ParserRule getParametroRule() {
		return getParametroAccess().getRule();
	}
	
	//enum TipoParametro:
	//	Path | Query | Body;
	public TipoParametroElements getTipoParametroAccess() {
		return eTipoParametro;
	}
	
	public EnumRule getTipoParametroRule() {
		return getTipoParametroAccess().getRule();
	}
	
	//terminal EQUAL:
	//	"=";
	public TerminalRule getEQUALRule() {
		return tEQUAL;
	}
	
	//terminal SEMICOLON:
	//	";";
	public TerminalRule getSEMICOLONRule() {
		return tSEMICOLON;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
