/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Inject
	private MyDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEntidadAccess().getAlternatives(), "rule__Entidad__Alternatives");
					put(grammarAccess.getAtributoAccess().getAlternatives(), "rule__Atributo__Alternatives");
					put(grammarAccess.getAtributoMockaAccess().getAlternatives_2_1(), "rule__AtributoMocka__Alternatives_2_1");
					put(grammarAccess.getUrlExpresionAccess().getAlternatives(), "rule__UrlExpresion__Alternatives");
					put(grammarAccess.getParametroAccess().getAlternatives(), "rule__Parametro__Alternatives");
					put(grammarAccess.getResponseAccess().getAlternatives_4(), "rule__Response__Alternatives_4");
					put(grammarAccess.getRequestAccess().getAlternatives_4(), "rule__Request__Alternatives_4");
					put(grammarAccess.getTipoEntidadAccess().getAlternatives(), "rule__TipoEntidad__Alternatives");
					put(grammarAccess.getDatoPrimitivoAccess().getAlternatives(), "rule__DatoPrimitivo__Alternatives");
					put(grammarAccess.getMappingAccess().getAlternatives_6(), "rule__Mapping__Alternatives_6");
					put(grammarAccess.getAsercionAccess().getAlternatives_0(), "rule__Asercion__Alternatives_0");
					put(grammarAccess.getAsercionAccess().getAlternatives_2(), "rule__Asercion__Alternatives_2");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getTipoAtributoAccess().getAlternatives(), "rule__TipoAtributo__Alternatives");
					put(grammarAccess.getOperadorAccess().getAlternatives(), "rule__Operador__Alternatives");
					put(grammarAccess.getMockarooAccess().getAlternatives(), "rule__Mockaroo__Alternatives");
					put(grammarAccess.getTipoMetodoRestAccess().getAlternatives(), "rule__TipoMetodoRest__Alternatives");
					put(grammarAccess.getApiAccess().getGroup(), "rule__Api__Group__0");
					put(grammarAccess.getSimpleEntityAccess().getGroup(), "rule__SimpleEntity__Group__0");
					put(grammarAccess.getAtributoMockaAccess().getGroup(), "rule__AtributoMocka__Group__0");
					put(grammarAccess.getAtributoMockaAccess().getGroup_2(), "rule__AtributoMocka__Group_2__0");
					put(grammarAccess.getAtributoMockaAccess().getGroup_2_1_0(), "rule__AtributoMocka__Group_2_1_0__0");
					put(grammarAccess.getAtributoMockaAccess().getGroup_2_1_1(), "rule__AtributoMocka__Group_2_1_1__0");
					put(grammarAccess.getAtributoArregloAccess().getGroup(), "rule__AtributoArreglo__Group__0");
					put(grammarAccess.getAtributoSimpleAccess().getGroup(), "rule__AtributoSimple__Group__0");
					put(grammarAccess.getMockarooEntityAccess().getGroup(), "rule__MockarooEntity__Group__0");
					put(grammarAccess.getServicioRestAccess().getGroup(), "rule__ServicioRest__Group__0");
					put(grammarAccess.getUrlAccess().getGroup(), "rule__Url__Group__0");
					put(grammarAccess.getStringTypeAccess().getGroup(), "rule__StringType__Group__0");
					put(grammarAccess.getQueryParamAccess().getGroup(), "rule__QueryParam__Group__0");
					put(grammarAccess.getPathParamAccess().getGroup(), "rule__PathParam__Group__0");
					put(grammarAccess.getResponseAccess().getGroup(), "rule__Response__Group__0");
					put(grammarAccess.getResponseAccess().getGroup_5(), "rule__Response__Group_5__0");
					put(grammarAccess.getRequestAccess().getGroup(), "rule__Request__Group__0");
					put(grammarAccess.getRequestAccess().getGroup_5(), "rule__Request__Group_5__0");
					put(grammarAccess.getTestAccess().getGroup(), "rule__Test__Group__0");
					put(grammarAccess.getTestAccess().getGroup_12(), "rule__Test__Group_12__0");
					put(grammarAccess.getMappingAccess().getGroup(), "rule__Mapping__Group__0");
					put(grammarAccess.getMappingAccess().getGroup_6_0(), "rule__Mapping__Group_6_0__0");
					put(grammarAccess.getAsercionAccess().getGroup(), "rule__Asercion__Group__0");
					put(grammarAccess.getAsercionAccess().getGroup_0_2(), "rule__Asercion__Group_0_2__0");
					put(grammarAccess.getAsercionAccess().getGroup_2_1(), "rule__Asercion__Group_2_1__0");
					put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
					put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getApiAccess().getUrlAssignment_3(), "rule__Api__UrlAssignment_3");
					put(grammarAccess.getApiAccess().getEntidadesAssignment_5(), "rule__Api__EntidadesAssignment_5");
					put(grammarAccess.getApiAccess().getPrimitivetypesAssignment_6(), "rule__Api__PrimitivetypesAssignment_6");
					put(grammarAccess.getApiAccess().getServiciosRestAssignment_7(), "rule__Api__ServiciosRestAssignment_7");
					put(grammarAccess.getApiAccess().getTestsAssignment_8(), "rule__Api__TestsAssignment_8");
					put(grammarAccess.getSimpleEntityAccess().getNameAssignment_1(), "rule__SimpleEntity__NameAssignment_1");
					put(grammarAccess.getSimpleEntityAccess().getAtributosAssignment_3(), "rule__SimpleEntity__AtributosAssignment_3");
					put(grammarAccess.getAtributoMockaAccess().getTipoAssignment_0(), "rule__AtributoMocka__TipoAssignment_0");
					put(grammarAccess.getAtributoMockaAccess().getNameAssignment_1(), "rule__AtributoMocka__NameAssignment_1");
					put(grammarAccess.getAtributoMockaAccess().getPrimaryKeyAssignment_2_1_0_0(), "rule__AtributoMocka__PrimaryKeyAssignment_2_1_0_0");
					put(grammarAccess.getAtributoMockaAccess().getMockTypeAssignment_2_1_0_2(), "rule__AtributoMocka__MockTypeAssignment_2_1_0_2");
					put(grammarAccess.getAtributoMockaAccess().getMockTypeAssignment_2_1_1_2(), "rule__AtributoMocka__MockTypeAssignment_2_1_1_2");
					put(grammarAccess.getAtributoArregloAccess().getTipoAssignment_0(), "rule__AtributoArreglo__TipoAssignment_0");
					put(grammarAccess.getAtributoArregloAccess().getNameAssignment_3(), "rule__AtributoArreglo__NameAssignment_3");
					put(grammarAccess.getAtributoSimpleAccess().getTipoAssignment_0(), "rule__AtributoSimple__TipoAssignment_0");
					put(grammarAccess.getAtributoSimpleAccess().getNameAssignment_1(), "rule__AtributoSimple__NameAssignment_1");
					put(grammarAccess.getMyStringAccess().getNameAssignment(), "rule__MyString__NameAssignment");
					put(grammarAccess.getMyNumericAccess().getNameAssignment(), "rule__MyNumeric__NameAssignment");
					put(grammarAccess.getMyBooleanAccess().getNameAssignment(), "rule__MyBoolean__NameAssignment");
					put(grammarAccess.getMockarooEntityAccess().getNameAssignment_1(), "rule__MockarooEntity__NameAssignment_1");
					put(grammarAccess.getMockarooEntityAccess().getAtributosAssignment_3(), "rule__MockarooEntity__AtributosAssignment_3");
					put(grammarAccess.getServicioRestAccess().getMetodoAssignment_0(), "rule__ServicioRest__MetodoAssignment_0");
					put(grammarAccess.getServicioRestAccess().getNameAssignment_1(), "rule__ServicioRest__NameAssignment_1");
					put(grammarAccess.getServicioRestAccess().getUrlAssignment_5(), "rule__ServicioRest__UrlAssignment_5");
					put(grammarAccess.getServicioRestAccess().getRequestAssignment_7(), "rule__ServicioRest__RequestAssignment_7");
					put(grammarAccess.getServicioRestAccess().getResponseAssignment_8(), "rule__ServicioRest__ResponseAssignment_8");
					put(grammarAccess.getUrlAccess().getUrlexpresionsAssignment_1(), "rule__Url__UrlexpresionsAssignment_1");
					put(grammarAccess.getStringTypeAccess().getTextAssignment_2(), "rule__StringType__TextAssignment_2");
					put(grammarAccess.getQueryParamAccess().getNameAssignment_2(), "rule__QueryParam__NameAssignment_2");
					put(grammarAccess.getPathParamAccess().getNameAssignment_1(), "rule__PathParam__NameAssignment_1");
					put(grammarAccess.getResponseAccess().getTipoEntidadAssignment_4_0(), "rule__Response__TipoEntidadAssignment_4_0");
					put(grammarAccess.getResponseAccess().getTipoPrimitivoAssignment_4_1(), "rule__Response__TipoPrimitivoAssignment_4_1");
					put(grammarAccess.getRequestAccess().getTipoEntidadAssignment_4_0(), "rule__Request__TipoEntidadAssignment_4_0");
					put(grammarAccess.getRequestAccess().getTipoPrimitivoAssignment_4_1(), "rule__Request__TipoPrimitivoAssignment_4_1");
					put(grammarAccess.getPrimitiveTypeAccess().getNameAssignment(), "rule__PrimitiveType__NameAssignment");
					put(grammarAccess.getTestAccess().getServiceAssignment_6(), "rule__Test__ServiceAssignment_6");
					put(grammarAccess.getTestAccess().getDescripcionAssignment_10(), "rule__Test__DescripcionAssignment_10");
					put(grammarAccess.getTestAccess().getMappingsAssignment_12_2(), "rule__Test__MappingsAssignment_12_2");
					put(grammarAccess.getTestAccess().getAsertionsAssignment_15(), "rule__Test__AsertionsAssignment_15");
					put(grammarAccess.getMappingAccess().getParametroAssignment_2(), "rule__Mapping__ParametroAssignment_2");
					put(grammarAccess.getMappingAccess().getAtributoAssignment_6_0_1(), "rule__Mapping__AtributoAssignment_6_0_1");
					put(grammarAccess.getMappingAccess().getDatoprimitivoAssignment_6_1(), "rule__Mapping__DatoprimitivoAssignment_6_1");
					put(grammarAccess.getAsercionAccess().getElemento1Assignment_0_0(), "rule__Asercion__Elemento1Assignment_0_0");
					put(grammarAccess.getAsercionAccess().getElemento1Assignment_0_1(), "rule__Asercion__Elemento1Assignment_0_1");
					put(grammarAccess.getAsercionAccess().getElemento1Assignment_0_2_1(), "rule__Asercion__Elemento1Assignment_0_2_1");
					put(grammarAccess.getAsercionAccess().getOperadorAssignment_1(), "rule__Asercion__OperadorAssignment_1");
					put(grammarAccess.getAsercionAccess().getElemento2Assignment_2_0(), "rule__Asercion__Elemento2Assignment_2_0");
					put(grammarAccess.getAsercionAccess().getElemento2Assignment_2_1_1(), "rule__Asercion__Elemento2Assignment_2_1_1");
					put(grammarAccess.getElementoStatusAccess().getTipoAssignment(), "rule__ElementoStatus__TipoAssignment");
					put(grammarAccess.getElementoResponseAccess().getTipoAssignment(), "rule__ElementoResponse__TipoAssignment");
					put(grammarAccess.getElementoAtributoAccess().getAtributoAssignment(), "rule__ElementoAtributo__AtributoAssignment");
					put(grammarAccess.getElementoParametroAccess().getParametroAssignment(), "rule__ElementoParametro__ParametroAssignment");
					put(grammarAccess.getElementoPrimitivoAccess().getElementoPrimitivoAssignment(), "rule__ElementoPrimitivo__ElementoPrimitivoAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
