<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="xSoftware" nsURI="http://www.uniandes.edu.co/xsoftware" nsPrefix="xSoftware">
  <eClassifiers xsi:type="ecore:EClass" name="Api">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entidades" upperBound="-1"
        eType="#//Entidad" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primitivetypes" upperBound="-1"
        eType="#//PrimitiveType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviciosRest" upperBound="-1"
        eType="#//ServicioRest" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tests" upperBound="-1"
        eType="#//Test" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServicioRest">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entidades" upperBound="-1"
        eType="#//Entidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metodo" eType="#//TipoMetodoRest"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="response" lowerBound="1"
        eType="#//Response" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="request" eType="#//Request"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametros" upperBound="-1"
        eType="#//Parametro" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entidad" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtributoMocka" eSuperTypes="#//Atributo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mockType" eType="#//Mockaroo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Response">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipoEntidad" eType="#//Entidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoPrimitivo" eType="#//TipoAtributo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mynumeric" upperBound="-1"
        eType="#//MyNumeric" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descripcion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//Mapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" lowerBound="1"
        eType="#//ServicioRest"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asertions" upperBound="-1"
        eType="#//Asercion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asercion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementoPrimitivo2" eType="#//DatoPrimitivo"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operador" eType="#//Operador"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elemento1" eType="#//ElementoAsersion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elemento2" eType="#//ElementoAsersion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoMetodoRest">
    <eLiterals name="GET"/>
    <eLiterals name="POST" value="1"/>
    <eLiterals name="PUT" value="2"/>
    <eLiterals name="DELETE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//TipoAtributo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MyNumeric" eSuperTypes="#//DatoPrimitivo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MyString" eSuperTypes="#//DatoPrimitivo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MyBoolean" eSuperTypes="#//DatoPrimitivo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Mockaroo">
    <eLiterals name="FirstNameType"/>
    <eLiterals name="LastNameType" value="1"/>
    <eLiterals name="FamilyNameType" value="2"/>
    <eLiterals name="FullNameType" value="3"/>
    <eLiterals name="GenderType" value="4"/>
    <eLiterals name="EmailAddressType" value="5"/>
    <eLiterals name="PhoneType" value="6"/>
    <eLiterals name="CountryType" value="7"/>
    <eLiterals name="CityType" value="8"/>
    <eLiterals name="CountryCodeType" value="9"/>
    <eLiterals name="LatitudeType" value="10"/>
    <eLiterals name="LongitudType" value="11"/>
    <eLiterals name="RowNumberType" value="12"/>
    <eLiterals name="BooleanType" value="13"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtributoArreglo" eSuperTypes="#//Atributo"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametro" eType="#//Parametro"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datoprimitivo" eType="#//DatoPrimitivo"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributo" eType="#//Atributo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoAtributo">
    <eLiterals name="string"/>
    <eLiterals name="int" value="1"/>
    <eLiterals name="boolean" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleEntity" eSuperTypes="#//Entidad">
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributos" upperBound="-1"
        eType="#//AtributoSimple" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MockarooEntity" eSuperTypes="#//Entidad">
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributos" upperBound="-1"
        eType="#//Atributo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atributo" abstract="true" eSuperTypes="#//ElementoAsersion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="#//TipoAtributo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtributoSimple" eSuperTypes="#//Atributo"/>
  <eClassifiers xsi:type="ecore:EClass" name="Request">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipoEntidad" eType="#//Entidad"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoPrimitivo" eType="#//TipoAtributo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parametro" abstract="true" eSuperTypes="#//ElementoAsersion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BodyParam" eSuperTypes="#//Parametro"/>
  <eClassifiers xsi:type="ecore:EClass" name="PathParam" eSuperTypes="#//Parametro"/>
  <eClassifiers xsi:type="ecore:EClass" name="QueryParam" eSuperTypes="#//Parametro"/>
  <eClassifiers xsi:type="ecore:EClass" name="DatoPrimitivo" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Operador">
    <eLiterals name="Igual"/>
    <eLiterals name="Mayor" value="1"/>
    <eLiterals name="Menor" value="2"/>
    <eLiterals name="MayorIgual" value="3"/>
    <eLiterals name="MenorIgual" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementoAsersion"/>
</ecore:EPackage>
